const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const Product = require('./models/Product');
const User = require('./models/User');

const products = [
  {
    name: 'Royal Perpetual Chronograph',
    brand: 'Aurelian',
    description: 'A masterpiece of haute horlogerie, the Royal Perpetual Chronograph combines a perpetual calendar with a split-seconds chronograph. Crafted in 18k rose gold with a hand-guilloché dial.',
    price: 28500,
    originalPrice: 32000,
    category: 'luxury',
    images: [
      'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
      'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800',
      'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400',
    stock: 5,
    rating: 4.9,
    numReviews: 24,
    isFeatured: true,
    isNewArrival: false,
    badge: 'Bestseller',
    colors: ['Rose Gold', 'Yellow Gold', 'Platinum'],
    specs: {
      movement: 'Manual-winding, Cal. A-3970',
      caseMaterial: '18k Rose Gold',
      caseSize: '41mm',
      waterResistance: '30m',
      crystal: 'Sapphire, anti-reflective',
      strap: 'Alligator leather',
      powerReserve: '65 hours',
      functions: ['Hours', 'Minutes', 'Seconds', 'Perpetual Calendar', 'Chronograph'],
    },
  },
  {
    name: 'Submariner Elite 300',
    brand: 'Nautique',
    description: 'Built for the deep, the Submariner Elite 300 is a professional diving watch with 300m water resistance, a unidirectional rotating bezel, and luminescent hands for maximum legibility underwater.',
    price: 8900,
    originalPrice: 9500,
    category: 'sport',
    images: [
      'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800',
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800',
      'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=400',
    stock: 12,
    rating: 4.8,
    numReviews: 56,
    isFeatured: true,
    isNewArrival: false,
    badge: 'Top Rated',
    colors: ['Black', 'Blue', 'Green'],
    specs: {
      movement: 'Automatic, Cal. N-3135',
      caseMaterial: 'Oystersteel',
      caseSize: '40mm',
      waterResistance: '300m',
      crystal: 'Sapphire, cyclops lens',
      strap: 'Oyster bracelet',
      powerReserve: '70 hours',
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Rotating Bezel'],
    },
  },
  {
    name: 'Heritage Dress Watch',
    brand: 'Maison Blanc',
    description: 'Timeless elegance distilled into a slim dress watch. The Heritage features a silver sunburst dial, applied gold indices, and a hand-stitched leather strap. The perfect companion for formal occasions.',
    price: 3200,
    originalPrice: null,
    category: 'classic',
    images: [
      'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=800',
      'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800',
      'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=400',
    stock: 20,
    rating: 4.7,
    numReviews: 38,
    isFeatured: true,
    isNewArrival: true,
    badge: 'New',
    colors: ['Silver', 'Champagne', 'White'],
    specs: {
      movement: 'Automatic, Cal. MB-1001',
      caseMaterial: 'Stainless Steel',
      caseSize: '38mm',
      waterResistance: '50m',
      crystal: 'Sapphire',
      strap: 'Hand-stitched calfskin',
      powerReserve: '42 hours',
      functions: ['Hours', 'Minutes', 'Seconds', 'Date'],
    },
  },
  {
    name: 'Apex Smartwatch Pro',
    brand: 'Nexus',
    description: 'The Apex Smartwatch Pro bridges the gap between luxury and technology. With an AMOLED display, health monitoring, GPS, and a titanium case, it redefines what a smartwatch can be.',
    price: 1200,
    originalPrice: 1500,
    category: 'digital',
    images: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800',
      'https://images.unsplash.com/photo-1544117519-31a4b719223d?w=800',
      'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400',
    stock: 30,
    rating: 4.6,
    numReviews: 112,
    isFeatured: true,
    isNewArrival: true,
    badge: 'New Arrival',
    colors: ['Midnight Black', 'Arctic White', 'Ocean Blue'],
    specs: {
      movement: 'Digital / Smart OS',
      caseMaterial: 'Grade 5 Titanium',
      caseSize: '44mm',
      waterResistance: '100m',
      crystal: 'Gorilla Glass 6',
      strap: 'Fluoroelastomer',
      powerReserve: '7 days',
      functions: ['GPS', 'Heart Rate', 'SpO2', 'Sleep Tracking', 'NFC Payments'],
    },
  },
  {
    name: 'Tourbillon Skeleton',
    brand: 'Aurelian',
    description: 'An architectural marvel of watchmaking. The flying tourbillon is visible through the skeletonized dial, revealing the intricate mechanics within. Limited to 50 pieces worldwide.',
    price: 65000,
    originalPrice: null,
    category: 'luxury',
    images: [
      'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800',
      'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
      'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=400',
    stock: 3,
    rating: 5.0,
    numReviews: 8,
    isFeatured: true,
    isNewArrival: false,
    badge: 'Limited Edition',
    colors: ['Platinum', 'White Gold'],
    specs: {
      movement: 'Manual-winding, Flying Tourbillon',
      caseMaterial: 'Platinum 950',
      caseSize: '42mm',
      waterResistance: '30m',
      crystal: 'Sapphire front & back',
      strap: 'Crocodile leather',
      powerReserve: '80 hours',
      functions: ['Hours', 'Minutes', 'Flying Tourbillon'],
    },
  },
  {
    name: 'Speedmaster Moonphase',
    brand: 'Celestia',
    description: 'Inspired by lunar exploration, the Speedmaster Moonphase features a stunning moonphase complication with a hand-painted enamel moon disc, tachymeter bezel, and tri-color chronograph.',
    price: 5800,
    originalPrice: 6200,
    category: 'classic',
    images: [
      'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800',
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800',
      'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400',
    stock: 8,
    rating: 4.8,
    numReviews: 31,
    isFeatured: false,
    isNewArrival: false,
    badge: null,
    colors: ['Black', 'Blue', 'Silver'],
    specs: {
      movement: 'Automatic, Cal. C-9300',
      caseMaterial: 'Stainless Steel',
      caseSize: '44.25mm',
      waterResistance: '50m',
      crystal: 'Sapphire',
      strap: 'Leather / Bracelet',
      powerReserve: '60 hours',
      functions: ['Hours', 'Minutes', 'Seconds', 'Moonphase', 'Chronograph', 'Date'],
    },
  },
  {
    name: 'Pilot Chronograph GMT',
    brand: 'Aviator',
    description: 'Engineered for aviators, the Pilot Chronograph GMT tracks two time zones simultaneously with a 24-hour GMT hand. Anti-magnetic construction and a large crown for gloved operation.',
    price: 4200,
    originalPrice: null,
    category: 'sport',
    images: [
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800',
      'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800',
      'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=400',
    stock: 15,
    rating: 4.7,
    numReviews: 44,
    isFeatured: false,
    isNewArrival: false,
    badge: null,
    colors: ['Black', 'Green', 'Blue'],
    specs: {
      movement: 'Automatic, Cal. A-7750',
      caseMaterial: 'Stainless Steel',
      caseSize: '43mm',
      waterResistance: '100m',
      crystal: 'Sapphire, anti-reflective',
      strap: 'Calfskin leather',
      powerReserve: '48 hours',
      functions: ['Hours', 'Minutes', 'Seconds', 'GMT', 'Chronograph', 'Date'],
    },
  },
  {
    name: 'Ultra-Thin Minimalist',
    brand: 'Maison Blanc',
    description: 'At just 5.4mm thick, the Ultra-Thin Minimalist is a triumph of restraint. A clean white dial with no indices, a single hand, and a paper-thin case make it the ultimate statement in understatement.',
    price: 2100,
    originalPrice: null,
    category: 'classic',
    images: [
      'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800',
      'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800',
      'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=400',
    stock: 18,
    rating: 4.5,
    numReviews: 22,
    isFeatured: false,
    isNewArrival: true,
    badge: 'New',
    colors: ['White', 'Cream', 'Black'],
    specs: {
      movement: 'Manual-winding, Cal. MB-2001',
      caseMaterial: 'Titanium',
      caseSize: '36mm',
      waterResistance: '30m',
      crystal: 'Sapphire',
      strap: 'Satin',
      powerReserve: '38 hours',
      functions: ['Hours', 'Minutes'],
    },
  },
  {
    name: 'Tactical Field Watch',
    brand: 'Ranger',
    description: 'Designed for extreme conditions, the Tactical Field Watch features a shock-resistant case, tritium illumination, and a scratch-proof DLC coating. Trusted by professionals worldwide.',
    price: 890,
    originalPrice: 1100,
    category: 'sport',
    images: [
      'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800',
      'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
      'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=400',
    stock: 25,
    rating: 4.6,
    numReviews: 78,
    isFeatured: false,
    isNewArrival: false,
    badge: 'Sale',
    colors: ['Matte Black', 'Olive Drab', 'Coyote Tan'],
    specs: {
      movement: 'Automatic, ETA 2824-2',
      caseMaterial: 'DLC-coated Steel',
      caseSize: '42mm',
      waterResistance: '200m',
      crystal: 'Sapphire',
      strap: 'NATO nylon',
      powerReserve: '42 hours',
      functions: ['Hours', 'Minutes', 'Seconds', 'Date'],
    },
  },
  {
    name: 'Diamond Pavé Glamour',
    brand: 'Lumière',
    description: 'A dazzling display of craftsmanship, the Diamond Pavé Glamour features 248 brilliant-cut diamonds set in 18k white gold. The mother-of-pearl dial shimmers with every movement.',
    price: 18500,
    originalPrice: null,
    category: 'luxury',
    images: [
      'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800',
      'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800',
      'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=400',
    stock: 4,
    rating: 4.9,
    numReviews: 15,
    isFeatured: false,
    isNewArrival: false,
    badge: 'Exclusive',
    colors: ['White Gold', 'Rose Gold'],
    specs: {
      movement: 'Quartz, Cal. L-690',
      caseMaterial: '18k White Gold',
      caseSize: '34mm',
      waterResistance: '30m',
      crystal: 'Sapphire',
      strap: 'Satin with diamond clasp',
      powerReserve: '3 years battery',
      functions: ['Hours', 'Minutes', 'Seconds'],
    },
  },
  {
    name: 'Solar Titanium Explorer',
    brand: 'Nexus',
    description: 'Powered by light, the Solar Titanium Explorer never needs a battery change. With GPS timekeeping, a titanium case, and 200m water resistance, it is built for the modern adventurer.',
    price: 950,
    originalPrice: 1100,
    category: 'digital',
    images: [
      'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800',
      'https://images.unsplash.com/photo-1544117519-31a4b719223d?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=400',
    stock: 22,
    rating: 4.5,
    numReviews: 67,
    isFeatured: false,
    isNewArrival: false,
    badge: 'Sale',
    colors: ['Titanium', 'Black', 'Blue'],
    specs: {
      movement: 'Solar-powered Quartz',
      caseMaterial: 'Titanium',
      caseSize: '46mm',
      waterResistance: '200m',
      crystal: 'Mineral glass',
      strap: 'Resin',
      powerReserve: '6 months in dark',
      functions: ['GPS', 'Solar Charging', 'World Time', 'Compass', 'Altimeter'],
    },
  },
  {
    name: 'Vintage Diver 1968',
    brand: 'Nautique',
    description: 'A faithful reissue of the iconic 1968 diver, the Vintage Diver 1968 features a gilt dial, pencil hands, and a domed crystal that captures the spirit of the golden age of diving watches.',
    price: 3600,
    originalPrice: null,
    category: 'classic',
    images: [
      'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800',
      'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800',
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400',
    stock: 10,
    rating: 4.8,
    numReviews: 29,
    isFeatured: false,
    isNewArrival: false,
    badge: null,
    colors: ['Gilt', 'Tropical Brown', 'Matte Black'],
    specs: {
      movement: 'Automatic, Cal. N-1520',
      caseMaterial: 'Stainless Steel',
      caseSize: '38mm',
      waterResistance: '200m',
      crystal: 'Domed acrylic',
      strap: 'Tropic rubber',
      powerReserve: '42 hours',
      functions: ['Hours', 'Minutes', 'Seconds', 'Date'],
    },
  },
  {
    name: 'Carbon Fiber Racing',
    brand: 'Aviator',
    description: 'Born on the racetrack, the Carbon Fiber Racing watch features a forged carbon case, a tachymeter scale, and a flyback chronograph. Lightweight, aggressive, and unmistakably fast.',
    price: 6500,
    originalPrice: 7200,
    category: 'sport',
    images: [
      'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
      'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800',
      'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400',
    stock: 7,
    rating: 4.7,
    numReviews: 33,
    isFeatured: false,
    isNewArrival: true,
    badge: 'New',
    colors: ['Carbon Black', 'Red Accent', 'Yellow Accent'],
    specs: {
      movement: 'Automatic, Cal. A-7750',
      caseMaterial: 'Forged Carbon',
      caseSize: '45mm',
      waterResistance: '100m',
      crystal: 'Sapphire',
      strap: 'Rubber racing strap',
      powerReserve: '48 hours',
      functions: ['Hours', 'Minutes', 'Seconds', 'Flyback Chronograph', 'Tachymeter'],
    },
  },
  {
    name: 'Enamel Grand Complication',
    brand: 'Aurelian',
    description: 'The pinnacle of Aurelian craftsmanship, featuring a hand-painted enamel dial depicting the celestial sphere, a minute repeater, perpetual calendar, and tourbillon. A true grand complication.',
    price: 120000,
    originalPrice: null,
    category: 'luxury',
    images: [
      'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800',
      'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
      'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=400',
    stock: 1,
    rating: 5.0,
    numReviews: 3,
    isFeatured: false,
    isNewArrival: false,
    badge: 'Ultra Rare',
    colors: ['Yellow Gold'],
    specs: {
      movement: 'Manual-winding, Grand Complication',
      caseMaterial: '18k Yellow Gold',
      caseSize: '44mm',
      waterResistance: '30m',
      crystal: 'Sapphire',
      strap: 'Alligator',
      powerReserve: '72 hours',
      functions: ['Tourbillon', 'Minute Repeater', 'Perpetual Calendar', 'Moonphase'],
    },
  },
  {
    name: 'Fitness Tracker Elite',
    brand: 'Nexus',
    description: 'The Fitness Tracker Elite combines advanced health monitoring with a sleek design. Track your workouts, sleep, stress levels, and more with medical-grade sensors in a premium package.',
    price: 450,
    originalPrice: 550,
    category: 'digital',
    images: [
      'https://images.unsplash.com/photo-1544117519-31a4b719223d?w=800',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800',
      'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1544117519-31a4b719223d?w=400',
    stock: 40,
    rating: 4.4,
    numReviews: 156,
    isFeatured: false,
    isNewArrival: false,
    badge: 'Sale',
    colors: ['Black', 'Rose Gold', 'Silver'],
    specs: {
      movement: 'Digital Smart OS',
      caseMaterial: 'Aluminum',
      caseSize: '40mm',
      waterResistance: '50m',
      crystal: 'Gorilla Glass',
      strap: 'Silicone',
      powerReserve: '14 days',
      functions: ['Heart Rate', 'SpO2', 'ECG', 'Sleep', 'Stress', 'GPS'],
    },
  },
  {
    name: 'Regatta Sailing Timer',
    brand: 'Nautique',
    description: 'Designed for competitive sailing, the Regatta features a countdown timer for race starts, a tide indicator, and a compass. Water-resistant to 300m with a helium escape valve.',
    price: 7800,
    originalPrice: null,
    category: 'sport',
    images: [
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800',
      'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800',
      'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=400',
    stock: 9,
    rating: 4.7,
    numReviews: 21,
    isFeatured: false,
    isNewArrival: true,
    badge: 'New',
    colors: ['Blue', 'White', 'Orange'],
    specs: {
      movement: 'Automatic, Cal. N-4130',
      caseMaterial: 'Ceramic & Steel',
      caseSize: '44mm',
      waterResistance: '300m',
      crystal: 'Sapphire',
      strap: 'Rubber',
      powerReserve: '70 hours',
      functions: ['Regatta Timer', 'Tide Indicator', 'Compass', 'Chronograph'],
    },
  },
  {
    name: 'Art Deco Revival',
    brand: 'Maison Blanc',
    description: 'Drawing inspiration from the 1920s Art Deco movement, this rectangular watch features a lacquered dial with geometric patterns, a hand-engraved case, and a deployant clasp.',
    price: 4800,
    originalPrice: null,
    category: 'classic',
    images: [
      'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800',
      'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800',
      'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=400',
    stock: 6,
    rating: 4.6,
    numReviews: 17,
    isFeatured: false,
    isNewArrival: false,
    badge: null,
    colors: ['Black Lacquer', 'Ivory', 'Midnight Blue'],
    specs: {
      movement: 'Manual-winding, Cal. MB-3001',
      caseMaterial: 'Yellow Gold Plated',
      caseSize: '28x38mm',
      waterResistance: '30m',
      crystal: 'Sapphire',
      strap: 'Lizard leather',
      powerReserve: '45 hours',
      functions: ['Hours', 'Minutes'],
    },
  },
  {
    name: 'Hybrid Smartwatch Prestige',
    brand: 'Celestia',
    description: 'The best of both worlds — the Hybrid Smartwatch Prestige looks like a traditional watch but hides smart features inside. Track activity, receive notifications, and control your music without a screen.',
    price: 680,
    originalPrice: 800,
    category: 'digital',
    images: [
      'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800',
      'https://images.unsplash.com/photo-1544117519-31a4b719223d?w=800',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=400',
    stock: 28,
    rating: 4.3,
    numReviews: 89,
    isFeatured: false,
    isNewArrival: false,
    badge: 'Sale',
    colors: ['Rose Gold', 'Silver', 'Gunmetal'],
    specs: {
      movement: 'Hybrid Quartz + Smart',
      caseMaterial: 'Stainless Steel',
      caseSize: '40mm',
      waterResistance: '50m',
      crystal: 'Mineral glass',
      strap: 'Leather',
      powerReserve: '2 years battery',
      functions: ['Activity Tracking', 'Notifications', 'Music Control', 'Sleep'],
    },
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    await Product.deleteMany({});
    await User.deleteMany({});

    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products`);

    await User.create({
      name: 'Admin User',
      email: 'admin@chronos.com',
      password: 'admin123',
      isAdmin: true,
    });
    await User.create({
      name: 'John Doe',
      email: 'john@example.com',
      password: 'password123',
    });
    console.log('Seeded users');

    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seed();
